### PR TITLE
Update README with Example

### LINKED ISSUE #18: Add examples to README
All examples are currently in an `examples` directory, but we should perhaps include the basic on on the README itself

### PR DESCRIPTION
**Pull request by mfix22**
Closes #18 
CC: @pranaygp

### CODE REVIEW

**Comment by pranaygp** [comment]
Thanks for helping @mfix22 

I wonder if we can have a smaller example rather that just showcases the API, and direct them to `/examples` for more (which you've already done 😄).

Maybe something like:
```javascript
const Sema = require('async-sema');
const s = new Sema(4, { capactiy: 100 }) // 4 async calls in "parallel", upto 100 async calls on this sema

async function fetchData() {
  await s.acquire()
  console.log(s.nrWaiting() + ' calls to fetch are waiting')
  // ... do some long async stuff
  s.release()
}

for(let i = 0; i < 100; i++) {
  fetchData()
}
```

What do you think?

**Comment by mfix22** [comment]
@pranaygp I was thinking the same thing, but didn't know if you wanted a working example or a "stub" example. Updating . . . .

**Comment by pranaygp** [comment]
this should still be a working example right?

**Comment by mfix22** [comment]
@pranaygp definitely, i was just referring to the "... do some long async stuff" 😄

**Pull request merged**
